config/routes.rb
NiftyNotes::Application.routes.draw do
  resources :comments

  root :to => "notes#index"
  resources :notes

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  validates :comment, :presence => true
  validates :note_id, :presence => true

  belongs_to :note
end

app/models/note.rb
class Note < ActiveRecord::Base
  validates_presence_of :title, :text
  
  has_many :posts, :dependent => :destroy 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout :choose_layout

  def choose_layout
    request.xhr?? false : 'application'
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def edit
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new(params[:comment])
  end
  
  def create
    @comment = Comment.new(params[:comment])
    if @comment.save
      redirect_to(note_path(params[:note_id]), :notice => 'Comment was successfully created.')
    else
      redirect_to(note_path(params[:note_id]), :notice => 'Error! Comment was\'nt created.')
    end
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update_attributes(params[:comment])
      redirect_to(note_path(params[:note_id]), :notice => 'Comment was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    
    redirect_to(note_path(params[:note_id]))
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.paginate(:page => params[:page], :per_page => 6)
  end

  def new
    @note = Note.new
  end

  def show
    @note = Note.find(params[:id])
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])

    if @note.update_attributes(params[:comment])
      redirect_to(note_path(params[:note_id]), :notice => 'Note was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def create
    @note = Note.create(params[:note])
    if @note.persisted?
      redirect_to notes_path
    else
      render :new
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy
  end
	 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
  def first_word(title)
    title.gsub /\s+.*/, ''
  end

  def next_words(title)
    title.gsub /^[^\s]+/, ''
  end
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :note_id %><br />
    <%= f.number_field :note_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Comment</th>
    <th>Note</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.comment %></td>
    <td><%= comment.note_id %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render :partial => "/notes/comments_form" %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Comment:</b>
  <%= @comment.comment %>
</p>

<p>
  <b>Note:</b>
  <%= @comment.note_id %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NiftyNotes</title>
    <%= stylesheet_link_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="sandbox">
      <h1 class="app-title">Nifty <%= link_to "Notes", notes_path %></h1>
      <%= yield %>
    </div>

    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/nifty_notes/index.html.erb
<!-- start slipsum code

Do you see any Teletubbies in here? Do you see a slender plastic tag clipped to my shirt with my name printed on it? Do you see a little Asian child with a blank expression on his face sitting outside on a mechanical helicopter that shakes when you put quarters in it? No? Well, that's what you see at a toy store. And you must think you're in a toy store, because you're here shopping for an infant named Jeb.

Well, the way they make shows is, they make one show. That show's called a pilot. Then they show that show to the people who make shows, and on the strength of that one show they decide if they're going to make more shows. Some pilots get picked and become television programs. Some don't, become nothing. She starred in one of the ones that became nothing.

You think water moves fast? You should see ice. It moves like it has a mind. Like it knows it killed the world once and got a taste for murder. After the avalanche, it took us a week to climb out. Now, I don't know exactly when we turned on each other, but I know that seven of us survived the slide... and only five made it out. Now we took an oath, that I'm breaking now. We said we'd say it was the snow that killed the other two, but it wasn't. Nature is lethal but it doesn't hold a candle to man.

The path of the righteous man is beset on all sides by the iniquities of the selfish and the tyranny of evil men. Blessed is he who, in the name of charity and good will, shepherds the weak through the valley of darkness, for he is truly his brother's keeper and the finder of lost children. And I will strike down upon thee with great vengeance and furious anger those who would attempt to poison and destroy My brothers. And you will know My name is the Lord when I lay My vengeance upon thee.

My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. Hey, look at me when I'm talking to you, motherfucker. You listen: we go in there, and that nigga Winston or anybody else is in there, you the first motherfucker to get shot. You understand?

My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. Hey, look at me when I'm talking to you, motherfucker. You listen: we go in there, and that nigga Winston or anybody else is in there, you the first motherfucker to get shot. You understand?

Your bones don't break, mine do. That's clear. Your cells react to bacteria and viruses differently than mine. You don't get sick, I do. That's also clear. But for some reason, you and I react the exact same way to water. We swallow it too fast, we choke. We get some in our lungs, we drown. However unreal it may seem, we are connected, you and I. We're on the same curve, just on opposite ends.

Your bones don't break, mine do. That's clear. Your cells react to bacteria and viruses differently than mine. You don't get sick, I do. That's also clear. But for some reason, you and I react the exact same way to water. We swallow it too fast, we choke. We get some in our lungs, we drown. However unreal it may seem, we are connected, you and I. We're on the same curve, just on opposite ends.

Do you see any Teletubbies in here? Do you see a slender plastic tag clipped to my shirt with my name printed on it? Do you see a little Asian child with a blank expression on his face sitting outside on a mechanical helicopter that shakes when you put quarters in it? No? Well, that's what you see at a toy store. And you must think you're in a toy store, because you're here shopping for an infant named Jeb.

Now that there is the Tec-9, a crappy spray gun from South Miami. This gun is advertised as the most popular gun in American crime. Do you believe that shit? It actually says that in the little book that comes with it: the most popular gun in American crime. Like they're actually proud of that shit.


end slipsum code -->

<div class="sandbox">
  <h1 class="app-title">Nifty Notes</h1>
  <div class="first-row">
    <% 3.times do %>
      <%= render 'note_preview' %>
    <% end %>
  </div>
  <div class="search-row">
    <input type="text" class="search-query" placeholder="What do you want to find?" />
    <input type="submit" class="search-button" value="Find it!" />
  </div>
  <div class="second-row">
    <% 3.times do %>
      <%= render 'note_preview' %>
    <% end %>
  </div>
  <div class="pagination">
    <a class="go-back" href="#">Go back</a>
    <% 3.times do %>
      <a class="page" href="#">123</a>
    <% end %>
  </div>
</div>

app/views/notes/_comment.html.erb
<div id = 'comments'>
  
  <div>
    <br /> 
    <%= link_to("delete", comment_path(comment, { :note_id => @note.id }), :method => :delete) %> 
  </div>
  <div>
    <%= comment.comment %>
    <br />
  </div>

</div>

app/views/notes/_comments_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment, :size => "67x5"%>
  </div>
  
  <%= hidden_field_tag :note_id, params[:note_id] ? params[:note_id] : @note.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <%= render :partial => 'shared/errors_for', :object => f.object %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :text %>
  <%= f.text_area :text %>
  <%= f.submit "Create!", :id => "note_submit" %>
<% end %>

app/views/notes/_note_preview.html.erb
<div class="note-preview">
  <h2>
    <%= link_to first_word(note_preview.title), note_path(note_preview) %>
    <%= next_words(note_preview.title) %>
  </h2>
  <div class="note-content">
    <%= note_preview.text %>
  </div>
  <div class="note-text-eater"><!-- --></div>
</div>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h2 class="action-new"><%= link_to 'New!', new_note_path, :class => "fancybox" %></h2>
<div class="first-row">
  <% @notes[0, 3].try(:each) do |note| %>
    <%= render :partial => 'note_preview', :object => note %>
  <% end %>
</div>
<div class="search-row">
  <input type="text" class="search-query" placeholder="What do you want to find?" />
  <input type="submit" class="search-button" value="Find!" />
</div>
<div class="second-row">
  <% @notes[3, 3].try(:each) do |note| %>
    <%= render :partial => 'note_preview', :object => note %>
  <% end %>
</div>
<%= will_paginate @notes %>

app/views/notes/new.html.erb
<%= render 'form' %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>
	 
<h1> <%= @note.title %> </h1>

<br />
<%= @note.text %>

<br />
<%= link_to 'Edit', edit_note_path(@note) %>
<%= link_to("Destroy", :method => :delete, :confirm => "Are you sure?") %>
<%= link_to 'Back', notes_path %>
<%= render 'comment' %>
<%= render 'comments_form' %>

app/views/shared/_errors_for.html.erb
<% unless errors_for.errors.count.zero? %>
  <ol class="error-description">
    <% errors_for.errors.each do |field, error| %>
      <li>
        <a href="#<%= "#{errors_for.class}_#{field}".underscore %>"><%= field.capitalize %></a>
        <%= error %>
      </li>
    <% end %>
  </ol>
<% end %>